apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sqlite
spec:
  serviceName: sqlite
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sqlite
  template:
    metadata:
      labels:
        app: sqlite
    spec:
      initContainers:
        - name: init-db
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command:
            - sh
            - -c
            - |
              apk add --no-cache sqlite
              sqlite3 {{ .Values.sqliteDb }} < /schema/schema.sql
              echo "✓ SQLite DB initialized at {{ .Values.sqliteDb }}"
          volumeMounts:
          - name: data
            mountPath: {{ .Values.persistence.mountPath }}
          - name: schema
            mountPath: /schema

      containers:
        - name: sqlite
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ["tail", "-f", "/dev/null"]
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          volumeMounts:
          - name: data
            mountPath: {{ .Values.persistence.mountPath }}
          livenessProbe:
            exec:
              command: ["test", "-f", "{{ .Values.sqliteDb }}"]
            initialDelaySeconds: 5
            periodSeconds: 10

      volumes:
      - name: schema
        configMap:
          name: sqlite-schema

  # Persistent Volume Claim
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.persistence.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}