apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-exporter
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-exporter
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
