apiVersion: v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: mysql
spec:
  serviceName: mysql
  replicas: {{ .Values.mysql.replicas }}
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}:{{ .Values.mysql.tag }}
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database | quote }}
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password

          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: config
              mountPath: /etc/mysql/conf.d

          resources:
            requests:
              memory: {{ .Values.mysql.resources.requests.memory | quote }}
              cpu: {{ .Values.mysql.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.mysql.resources.limits.memory | quote }}
              cpu: {{ .Values.mysql.resources.limits.cpu | quote }}

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  mysqladmin ping -u root -p$MYSQL_ROOT_PASSWORD
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  mysqladmin ping -u root -p$MYSQL_ROOT_PASSWORD
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          {{ if .Values.nodeSelector }}
            nodeSelector:
              {{ toYaml .Values.nodeSelector | nindent 8 }}
          {{ end }}

          {{ if .Values.tolerations }}
            tolerations:
              {{ toYaml .Values.tolerations | nindent 8 }}
          {{ end }}

          volumes:
          - name: config
            configMap:
              name: mysql-config

  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.storage.storageClassName | quote }}
      resources:
        requests:
          storage: {{ .Values.storage.size | quote }}