{{- if .Values.ingress.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ingress.tls.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: orderflow
spec:
  secretName: {{ .Values.ingress.tls.secretName }}
  duration: 2160h  # 90 days
  renewBefore: 720h  # 30 days
  commonName: {{ .Values.ingress.host }}
  dnsNames:
    - {{ .Values.ingress.host }}
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
{{- end }}
