apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-orderflow
  labels:
    app: orderflow
spec:
  selector:
    matchLabels:
      app: orderflow
  strategy:
    canary:
      steps:
        {{- toYaml .Values.canarySteps | nindent 8 }}
  template:
    metadata:
      labels:
        app: orderflow
    spec:
      containers:
        - name: orderflow
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      imagePullSecrets:
        - name: ghcr-secret

