apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orderflow-app
spec:
  project: default
  source:
    repoURL: https://github.com/PiotrSacharuk/various-trainings.gitops
    path: orderflow
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true