apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sqlite-statefulset
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PiotrSacharuk/various-trainings.gitops
    path: sqlite-statefulset
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: sqlite
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true